### PR TITLE
Adding Firing functions

### PR DESCRIPTION
**Pull request by ASladek**
Conversion of our current model to Gson/Json isn't complete, which makes interaction with front end difficult, but this is a rough firing function.

### CODE REVIEW

**Comment by narxy** [comment]
does anything prevent it from registering a hit on the same spot more than once?

**Comment by RyanRapp14** [comment]
Looks like your function should work for the current placement of the computer's ships.

**Comment by ASladek** [comment]
Hitting on the same spot twice should be prevented by the server's response, not the check_fire function.

**Comment by ASladek** [comment]
So no, it hasn't been implemented.

**Comment by narxy** [comment]
okay cool

**Pull request merged**
